/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.28
 * Generated at: 2016-05-13 01:25:50 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import Bean.EmployeeDetails;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.Statement;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.math.*;
import java.text.DecimalFormat;

public final class EmployeeDetails_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("file:/C:/Program%20Files/apache-tomcat-8.0.28/lib/jstl-1.2.jar", Long.valueOf(1383066250000L));
    _jspx_dependants.put("jar:file:/C:/Program%20Files/apache-tomcat-8.0.28/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153410282000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("java.math");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.sql.Connection");
    _jspx_imports_classes.add("java.sql.ResultSet");
    _jspx_imports_classes.add("java.sql.Statement");
    _jspx_imports_classes.add("java.text.DecimalFormat");
    _jspx_imports_classes.add("Bean.EmployeeDetails");
    _jspx_imports_classes.add("java.sql.PreparedStatement");
    _jspx_imports_classes.add("java.sql.DriverManager");
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.release();
    _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("\r\n");
      out.write("\r\n");


HttpSession s2=request.getSession();
String uname=(String)s2.getAttribute("user");
//HttpSession[] s3=request.getSession();

try
{
	
Class.forName("com.mysql.jdbc.Driver");
 String url = "jdbc:mysql://us-cdbr-azure-west-c.cloudapp.net:3306/acsm_90810a19358144c?useSSL=false";
 String username = "b475de1c4476f1";
String password = "a5706aa1";
String query="select * from employees where email!=?";
int totalemp=0,totalprod=0,totalcust=0,totalord=0;
int total=0;
Connection conn=DriverManager.getConnection(url,username,password);
PreparedStatement stmt=conn.prepareStatement("select * from employees where email!=?");
PreparedStatement stmt2=conn.prepareStatement("select distinct(productVendor) from products");
PreparedStatement stmt3=conn.prepareStatement("Select sum(quantityInStock) from products where productVendor=?");
PreparedStatement stmt4=conn.prepareStatement("select distinct(productLine) from products");
PreparedStatement stmt5=conn.prepareStatement("Select sum(quantityInStock) from products where productLine=?");
PreparedStatement stmt6=conn.prepareStatement("Select sum(quantityInStock) from products");
PreparedStatement stmt7=conn.prepareStatement("Select count(employeeNumber) from employees");
PreparedStatement stmt8=conn.prepareStatement("Select count(productCode) from products");
PreparedStatement stmt9=conn.prepareStatement("Select count(customerNumber) from customers");
PreparedStatement stmt10=conn.prepareStatement("Select count(orderNumber) from orders");
ResultSet rs10=stmt10.executeQuery();
ResultSet rs9=stmt9.executeQuery();
ResultSet rs2=stmt2.executeQuery();
ResultSet rs4=stmt4.executeQuery();
ResultSet rs6=stmt6.executeQuery();
ResultSet rs7=stmt7.executeQuery();
ResultSet rs8=stmt8.executeQuery();
while(rs6.next()){
	 total=rs6.getInt(1);
	 
}
while(rs7.next()){
totalemp=rs7.getInt(1);
s2.setAttribute("totalemp",totalemp);
}
while(rs8.next()){
totalprod=rs8.getInt(1);
s2.setAttribute("totalprod",totalprod);
}

while(rs9.next()){
totalcust=rs9.getInt(1);
s2.setAttribute("totalcust",totalcust);
}
while(rs10.next()){
totalord=rs10.getInt(1);
s2.setAttribute("totalord",totalord);
}
ResultSet rs3,rs5;
int a[]=new int[50];
int b[]=new int[50];
String aa[]=new String[50];
String bb[]=new String[50];
int i=0;
stmt.setString(1,"dmurphy@classicmodelcars.com" );
ResultSet rs=stmt.executeQuery();
DecimalFormat df = new DecimalFormat("#.####");
df.setRoundingMode(RoundingMode.CEILING);

while(rs.next())
{


System.out.println(rs.getString(1));

}
System.out.println("Ordered by product vendors\n");
while (rs2.next()){
	stmt3.setString(1,rs2.getString(1));
	rs3=stmt3.executeQuery();
	while(rs3.next()){
		a[i]=rs3.getInt(1);
		aa[i]=df.format(((double)a[i]/(double)total)*100);
		s2.setAttribute("aa "+i, aa[i]);
		s2.setAttribute("ven"+i,rs2.getString(1));
		//System.out.println(total);
		System.out.println(rs2.getString(1)+": "+aa[i]);
		i++;
	}
}
System.out.println("\n\n");
System.out.println("Ordered by product Lines\n\n");
while (rs4.next()){
	stmt5.setString(1,rs4.getString(1));
	rs5=stmt5.executeQuery();
	while(rs5.next()){
		b[i]=rs5.getInt(1);
		bb[i]=df.format(((double)b[i]/(double)total)*100);
		s2.setAttribute("bb "+i, bb[i]);
		s2.setAttribute("plines"+i,rs4.getString(1));
		System.out.println(rs4.getString(1)+": "+bb[i]);
		i++;
	}
}	
	
	rs7.close();
    stmt7.close();
	rs6.close();
    stmt6.close();
	//rs5.close();
    stmt5.close();
	rs4.close();
    stmt4.close();
	//rs3.close();
    stmt3.close();
    rs2.close();
    stmt2.close();
    rs.close();
    stmt.close();
    conn.close();
    }
catch(Exception e)
{
    e.printStackTrace();
    }





      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("\r\n");
      out.write(" <head>\r\n");
      out.write("    <meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("    <!-- Meta, title, CSS, favicons, etc. -->\r\n");
      out.write("    <meta charset=\"utf-8\">\r\n");
      out.write("    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("\t\r\n");
      out.write("     \r\n");
      out.write("     \r\n");
      out.write("        \r\n");
      out.write("\r\n");
      out.write("    <title>Avenger's Console! | </title>\r\n");
      out.write("\r\n");
      out.write("    <!-- Bootstrap -->\r\n");
      out.write("    <link href=\"../vendors/bootstrap/dist/css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("    <!-- Font Awesome -->\r\n");
      out.write("    <link href=\"../vendors/font-awesome/css/font-awesome.min.css\" rel=\"stylesheet\">\r\n");
      out.write("    <!-- iCheck -->\r\n");
      out.write("    <link href=\"../vendors/iCheck/skins/flat/green.css\" rel=\"stylesheet\">\r\n");
      out.write("    <!-- bootstrap-progressbar -->\r\n");
      out.write("    <link href=\"../vendors/bootstrap-progressbar/css/bootstrap-progressbar-3.3.4.min.css\" rel=\"stylesheet\">\r\n");
      out.write("    <!-- jVectorMap -->\r\n");
      out.write("    <link href=\"css/maps/jquery-jvectormap-2.0.3.css\" rel=\"stylesheet\"/>\r\n");
      out.write("\r\n");
      out.write("    <!-- Custom Theme Style -->\r\n");
      out.write("    <link href=\"css/custom.css\" rel=\"stylesheet\">\r\n");
      out.write("  </head>\r\n");
      out.write("\r\n");
      out.write("  <body class=\"nav-md\">\r\n");
      out.write("    <div class=\"container body\">\r\n");
      out.write("      <div class=\"main_container\">\r\n");
      out.write("        <div class=\"col-md-3 left_col\">\r\n");
      out.write("          <div class=\"left_col scroll-view\">\r\n");
      out.write("            <div class=\"navbar nav_title\" style=\"border: 0;\">\r\n");
      out.write("              <a href=\"index.html\" class=\"site_title\"><i class=\"fa fa-paw\"></i> <span>Avenger's Console!</span></a>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <div class=\"clearfix\"></div>\r\n");
      out.write("\r\n");
      out.write("            <!-- menu profile quick info -->\r\n");
      out.write("            <div class=\"profile\">\r\n");
      out.write("              <div class=\"profile_pic\">\r\n");
      out.write("                <img src=\"images/img.jpg\" alt=\"...\" class=\"img-circle profile_img\">\r\n");
      out.write("              </div>\r\n");
      out.write("              <div class=\"profile_info\">\r\n");
      out.write("                <span>Welcome,\r\n");
      out.write("                <h2>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${uname}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</h2>\r\n");
      out.write("        <input type=\"hidden\" name=\"user\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${uname}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"/>\r\n");
      out.write("                </span>\r\n");
      out.write("                \r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <!-- /menu profile quick info -->\r\n");
      out.write("\r\n");
      out.write("            <br />\r\n");
      out.write("\r\n");
      out.write("            <!-- sidebar menu -->\r\n");
      out.write("            <div id=\"sidebar-menu\" class=\"main_menu_side hidden-print main_menu\">\r\n");
      out.write("              <div class=\"menu_section\">\r\n");
      out.write("              ");
      if (_jspx_meth_c_005fforEach_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("                <li role=\"presentation\" class=\"dropdown\">\r\n");
      out.write("                  \r\n");
      out.write("                  <ul id=\"menu1\" class=\"dropdown-menu list-unstyled msg_list\" role=\"menu\">\r\n");
      out.write("                    <li>\r\n");
      out.write("                      <a>\r\n");
      out.write("                        <span class=\"image\">\r\n");
      out.write("                                          <img src=\"images/img.jpg\" alt=\"Profile Image\" />\r\n");
      out.write("                                      </span>\r\n");
      out.write("                        <span>\r\n");
      out.write("                                          <span>John Smith</span>\r\n");
      out.write("                        <span class=\"time\">3 mins ago</span>\r\n");
      out.write("                        </span>\r\n");
      out.write("                        <span class=\"message\">\r\n");
      out.write("                                          Film festivals used to be do-or-die moments for movie makers. They were where...\r\n");
      out.write("                                      </span>\r\n");
      out.write("                      </a>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li>\r\n");
      out.write("                      <a>\r\n");
      out.write("                        <span class=\"image\">\r\n");
      out.write("                                          <img src=\"images/img.jpg\" alt=\"Profile Image\" />\r\n");
      out.write("                                      </span>\r\n");
      out.write("                        <span>\r\n");
      out.write("                                          <span>John Smith</span>\r\n");
      out.write("                        <span class=\"time\">3 mins ago</span>\r\n");
      out.write("                        </span>\r\n");
      out.write("                        <span class=\"message\">\r\n");
      out.write("                                          Film festivals used to be do-or-die moments for movie makers. They were where...\r\n");
      out.write("                                      </span>\r\n");
      out.write("                      </a>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li>\r\n");
      out.write("                      <a>\r\n");
      out.write("                        <span class=\"image\">\r\n");
      out.write("                                          <img src=\"images/img.jpg\" alt=\"Profile Image\" />\r\n");
      out.write("                                      </span>\r\n");
      out.write("                        <span>\r\n");
      out.write("                                          <span>John Smith</span>\r\n");
      out.write("                        <span class=\"time\">3 mins ago</span>\r\n");
      out.write("                        </span>\r\n");
      out.write("                        <span class=\"message\">\r\n");
      out.write("                                          Film festivals used to be do-or-die moments for movie makers. They were where...\r\n");
      out.write("                                      </span>\r\n");
      out.write("                      </a>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li>\r\n");
      out.write("                      <a>\r\n");
      out.write("                        <span class=\"image\">\r\n");
      out.write("                                          <img src=\"images/img.jpg\" alt=\"Profile Image\" />\r\n");
      out.write("                                      </span>\r\n");
      out.write("                        <span>\r\n");
      out.write("                                          <span>John Smith</span>\r\n");
      out.write("                        <span class=\"time\">3 mins ago</span>\r\n");
      out.write("                        </span>\r\n");
      out.write("                        <span class=\"message\">\r\n");
      out.write("                                          Film festivals used to be do-or-die moments for movie makers. They were where...\r\n");
      out.write("                                      </span>\r\n");
      out.write("                      </a>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li>\r\n");
      out.write("                      <div class=\"text-center\">\r\n");
      out.write("                        <a href=\"inbox.html\">\r\n");
      out.write("                          <strong>See All Alerts</strong>\r\n");
      out.write("                          <i class=\"fa fa-angle-right\"></i>\r\n");
      out.write("                        </a>\r\n");
      out.write("                      </div>\r\n");
      out.write("                    </li>\r\n");
      out.write("                  </ul>\r\n");
      out.write("                </li>\r\n");
      out.write("\r\n");
      out.write("              </ul>\r\n");
      out.write("            </nav>\r\n");
      out.write("          </div>\r\n");
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("        <!-- /top navigation -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("        <!-- page content -->\r\n");
      out.write("        <div class=\"right_col\" role=\"main\">\r\n");
      out.write("\r\n");
      out.write("          <!-- top tiles -->\r\n");
      out.write("          <div class=\"row tile_count\">\r\n");
      out.write("            <div class=\"col-md-2 col-sm-4 col-xs-6 tile_stats_count\">\r\n");
      out.write("              <span class=\"count_top\"><i class=\"fa fa-user\"></i> Total Employees</span>\r\n");
      out.write("              <div class=\"count green\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${totalemp}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</div>\r\n");
      out.write("              <span class=\"count_bottom\"><i class=\"green\">  </span>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"col-md-2 col-sm-4 col-xs-6 tile_stats_count\">\r\n");
      out.write("              <span class=\"count_top\"><i class=\"fa fa-clock-o\"></i> Total Females</span>\r\n");
      out.write("              <div class=\"count green\">123.5000</div>\r\n");
      out.write("              <span class=\"count_bottom\"><i class=\"green\"> </span>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"col-md-2 col-sm-4 col-xs-6 tile_stats_count\">\r\n");
      out.write("              <span class=\"count_top\"><i class=\"fa fa-user\"></i> Total Males</span>\r\n");
      out.write("              <div class=\"count green\">2,500</div>\r\n");
      out.write("              <span class=\"count_bottom\"><i class=\"green\"></span>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"col-md-2 col-sm-4 col-xs-6 tile_stats_count\">\r\n");
      out.write("              <span class=\"count_top\"><i class=\"fa fa-user\"></i> Total Products</span>\r\n");
      out.write("              <div class=\"count green\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${totalprod}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</div>\r\n");
      out.write("              <span class=\"count_bottom\"><i class=\"red\"> </i> </span>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"col-md-2 col-sm-4 col-xs-6 tile_stats_count\">\r\n");
      out.write("              <span class=\"count_top\"><i class=\"fa fa-user\"></i> Total Customers</span>\r\n");
      out.write("              <div class=\"count\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${totalcust}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</div>\r\n");
      out.write("              <span class=\"count_bottom\"><i class=\"green\"> </i> </span>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"col-md-2 col-sm-4 col-xs-6 tile_stats_count\">\r\n");
      out.write("              <span class=\"count_top\"><i class=\"fa fa-user\"></i> Total Orders</span>\r\n");
      out.write("              <div class=\"count\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${totalord}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</div>\r\n");
      out.write("              <span class=\"count_bottom\"><i class=\"green\"><i class=\"fa fa-sort-asc\"></i> </i> </span>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("          <!-- /top tiles -->\r\n");
      out.write("\r\n");
      out.write("          <div class=\"row\">\r\n");
      out.write("            <div class=\"col-md-12 col-sm-12 col-xs-12\">\r\n");
      out.write("              <div class=\"dashboard_graph\">\r\n");
      out.write("\r\n");
      out.write("                <div class=\"row x_title\">\r\n");
      out.write("                  <div class=\"col-md-6\">\r\n");
      out.write("                    <h3>Network Activities <small>Graph title sub-title</small></h3>\r\n");
      out.write("                  </div>\r\n");
      out.write("                  <div class=\"col-md-6\">\r\n");
      out.write("                    \r\n");
      out.write("                  </div>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <div class=\"col-md-9 col-sm-9 col-xs-12\">\r\n");
      out.write("                  <div id=\"placeholder33\" style=\"height: 260px; display: none\" class=\"demo-placeholder\"></div>\r\n");
      out.write("                  <div style=\"width: 100%;\">\r\n");
      out.write("                    <div id=\"canvas_dahs\" class=\"demo-placeholder\" style=\"width: 100%; height:270px;\"></div>\r\n");
      out.write("                  </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col-md-3 col-sm-3 col-xs-12 bg-white\">\r\n");
      out.write("                  <div class=\"x_title\">\r\n");
      out.write("                    <h2>Top Campaign Performance</h2>\r\n");
      out.write("                    <div class=\"clearfix\"></div>\r\n");
      out.write("                  </div>\r\n");
      out.write("\r\n");
      out.write("                  <div class=\"col-md-12 col-sm-12 col-xs-6\">\r\n");
      out.write("                    <div>\r\n");
      out.write("                      <p>Facebook Campaign</p>\r\n");
      out.write("                      <div class=\"\">\r\n");
      out.write("                        <div class=\"progress progress_sm\" style=\"width: 76%;\">\r\n");
      out.write("                          <div class=\"progress-bar bg-green\" role=\"progressbar\" data-transitiongoal=\"80\"></div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                      </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div>\r\n");
      out.write("                      <p>Twitter Campaign</p>\r\n");
      out.write("                      <div class=\"\">\r\n");
      out.write("                        <div class=\"progress progress_sm\" style=\"width: 76%;\">\r\n");
      out.write("                          <div class=\"progress-bar bg-green\" role=\"progressbar\" data-transitiongoal=\"60\"></div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                      </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                  </div>\r\n");
      out.write("                  <div class=\"col-md-12 col-sm-12 col-xs-6\">\r\n");
      out.write("                    <div>\r\n");
      out.write("                      <p>Conventional Media</p>\r\n");
      out.write("                      <div class=\"\">\r\n");
      out.write("                        <div class=\"progress progress_sm\" style=\"width: 76%;\">\r\n");
      out.write("                          <div class=\"progress-bar bg-green\" role=\"progressbar\" data-transitiongoal=\"40\"></div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                      </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div>\r\n");
      out.write("                      <p>Bill boards</p>\r\n");
      out.write("                      <div class=\"\">\r\n");
      out.write("                        <div class=\"progress progress_sm\" style=\"width: 76%;\">\r\n");
      out.write("                          <div class=\"progress-bar bg-green\" role=\"progressbar\" data-transitiongoal=\"50\"></div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                      </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                  </div>\r\n");
      out.write("\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <div class=\"clearfix\"></div>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("          </div>\r\n");
      out.write("          <br />\r\n");
      out.write("\r\n");
      out.write("          <div class=\"row\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("            <div class=\"col-md-4 col-sm-4 col-xs-12\">\r\n");
      out.write("              <div class=\"x_panel tile fixed_height_320\">\r\n");
      out.write("                <div class=\"x_title\">\r\n");
      out.write("                  <h2>App Versions</h2>\r\n");
      out.write("                  <ul class=\"nav navbar-right panel_toolbox\">\r\n");
      out.write("                    <li><a class=\"collapse-link\"><i class=\"fa fa-chevron-up\"></i></a>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li class=\"dropdown\">\r\n");
      out.write("                      <a href=\"#\" class=\"dropdown-toggle\" data-toggle=\"dropdown\" role=\"button\" aria-expanded=\"false\"><i class=\"fa fa-wrench\"></i></a>\r\n");
      out.write("                      <ul class=\"dropdown-menu\" role=\"menu\">\r\n");
      out.write("                        <li><a href=\"#\">Settings 1</a>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li><a href=\"#\">Settings 2</a>\r\n");
      out.write("                        </li>\r\n");
      out.write("                      </ul>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li><a class=\"close-link\"><i class=\"fa fa-close\"></i></a>\r\n");
      out.write("                    </li>\r\n");
      out.write("                  </ul>\r\n");
      out.write("                  <div class=\"clearfix\"></div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"x_content\">\r\n");
      out.write("                  <h4>App Usage across versions</h4>\r\n");
      out.write("                  <div class=\"widget_summary\">\r\n");
      out.write("                    <div class=\"w_left w_25\">\r\n");
      out.write("                      <span>0.1.5.2</span>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"w_center w_55\">\r\n");
      out.write("                      <div class=\"progress\">\r\n");
      out.write("                        <div class=\"progress-bar bg-green\" role=\"progressbar\" aria-valuenow=\"60\" aria-valuemin=\"0\" aria-valuemax=\"100\" style=\"width: 66%;\">\r\n");
      out.write("                          <span class=\"sr-only\">60% Complete</span>\r\n");
      out.write("                        </div>\r\n");
      out.write("                      </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"w_right w_20\">\r\n");
      out.write("                      <span>123k</span>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"clearfix\"></div>\r\n");
      out.write("                  </div>\r\n");
      out.write("\r\n");
      out.write("                  <div class=\"widget_summary\">\r\n");
      out.write("                    <div class=\"w_left w_25\">\r\n");
      out.write("                      <span>0.1.5.3</span>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"w_center w_55\">\r\n");
      out.write("                      <div class=\"progress\">\r\n");
      out.write("                        <div class=\"progress-bar bg-green\" role=\"progressbar\" aria-valuenow=\"60\" aria-valuemin=\"0\" aria-valuemax=\"100\" style=\"width: 45%;\">\r\n");
      out.write("                          <span class=\"sr-only\">60% Complete</span>\r\n");
      out.write("                        </div>\r\n");
      out.write("                      </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"w_right w_20\">\r\n");
      out.write("                      <span>53k</span>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"clearfix\"></div>\r\n");
      out.write("                  </div>\r\n");
      out.write("                  <div class=\"widget_summary\">\r\n");
      out.write("                    <div class=\"w_left w_25\">\r\n");
      out.write("                      <span>0.1.5.4</span>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"w_center w_55\">\r\n");
      out.write("                      <div class=\"progress\">\r\n");
      out.write("                        <div class=\"progress-bar bg-green\" role=\"progressbar\" aria-valuenow=\"60\" aria-valuemin=\"0\" aria-valuemax=\"100\" style=\"width: 25%;\">\r\n");
      out.write("                          <span class=\"sr-only\">60% Complete</span>\r\n");
      out.write("                        </div>\r\n");
      out.write("                      </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"w_right w_20\">\r\n");
      out.write("                      <span>23k</span>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"clearfix\"></div>\r\n");
      out.write("                  </div>\r\n");
      out.write("                  <div class=\"widget_summary\">\r\n");
      out.write("                    <div class=\"w_left w_25\">\r\n");
      out.write("                      <span>0.1.5.5</span>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"w_center w_55\">\r\n");
      out.write("                      <div class=\"progress\">\r\n");
      out.write("                        <div class=\"progress-bar bg-green\" role=\"progressbar\" aria-valuenow=\"60\" aria-valuemin=\"0\" aria-valuemax=\"100\" style=\"width: 5%;\">\r\n");
      out.write("                          <span class=\"sr-only\">60% Complete</span>\r\n");
      out.write("                        </div>\r\n");
      out.write("                      </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"w_right w_20\">\r\n");
      out.write("                      <span>3k</span>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"clearfix\"></div>\r\n");
      out.write("                  </div>\r\n");
      out.write("                  <div class=\"widget_summary\">\r\n");
      out.write("                    <div class=\"w_left w_25\">\r\n");
      out.write("                      <span>0.1.5.6</span>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"w_center w_55\">\r\n");
      out.write("                      <div class=\"progress\">\r\n");
      out.write("                        <div class=\"progress-bar bg-green\" role=\"progressbar\" aria-valuenow=\"60\" aria-valuemin=\"0\" aria-valuemax=\"100\" style=\"width: 2%;\">\r\n");
      out.write("                          <span class=\"sr-only\">60% Complete</span>\r\n");
      out.write("                        </div>\r\n");
      out.write("                      </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"w_right w_20\">\r\n");
      out.write("                      <span>1k</span>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"clearfix\"></div>\r\n");
      out.write("                  </div>\r\n");
      out.write("\r\n");
      out.write("                </div>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <div class=\"col-md-4 col-sm-4 col-xs-12\">\r\n");
      out.write("              <div class=\"x_panel tile fixed_height_320 overflow_hidden\">\r\n");
      out.write("                <div class=\"x_title\">\r\n");
      out.write("                  <h2>Device Usage</h2>\r\n");
      out.write("                  <ul class=\"nav navbar-right panel_toolbox\">\r\n");
      out.write("                    <li><a class=\"collapse-link\"><i class=\"fa fa-chevron-up\"></i></a>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li class=\"dropdown\">\r\n");
      out.write("                      <a href=\"#\" class=\"dropdown-toggle\" data-toggle=\"dropdown\" role=\"button\" aria-expanded=\"false\"><i class=\"fa fa-wrench\"></i></a>\r\n");
      out.write("                      <ul class=\"dropdown-menu\" role=\"menu\">\r\n");
      out.write("                        <li><a href=\"#\">Settings 1</a>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li><a href=\"#\">Settings 2</a>\r\n");
      out.write("                        </li>\r\n");
      out.write("                      </ul>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li><a class=\"close-link\"><i class=\"fa fa-close\"></i></a>\r\n");
      out.write("                    </li>\r\n");
      out.write("                  </ul>\r\n");
      out.write("                  <div class=\"clearfix\"></div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"x_content\">\r\n");
      out.write("                  <table class=\"\" style=\"width:100%\">\r\n");
      out.write("                    <tr>\r\n");
      out.write("                      <th style=\"width:37%;\">\r\n");
      out.write("                        <p>Top 5</p>\r\n");
      out.write("                      </th>\r\n");
      out.write("                      <th>\r\n");
      out.write("                        <div class=\"col-lg-7 col-md-7 col-sm-7 col-xs-7\">\r\n");
      out.write("                          <p class=\"\">Device</p>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"col-lg-5 col-md-5 col-sm-5 col-xs-5\">\r\n");
      out.write("                          <p class=\"\">Progress</p>\r\n");
      out.write("                        </div>\r\n");
      out.write("                      </th>\r\n");
      out.write("                    </tr>\r\n");
      out.write("                    <tr>\r\n");
      out.write("                      <td>\r\n");
      out.write("                        <canvas id=\"canvas1\" height=\"140\" width=\"140\" style=\"margin: 15px 10px 10px 0\"></canvas>\r\n");
      out.write("                      </td>\r\n");
      out.write("                      <td>\r\n");
      out.write("                        <table class=\"tile_info\">\r\n");
      out.write("                          <tr>\r\n");
      out.write("                            <td>\r\n");
      out.write("                              <p><i class=\"fa fa-square blue\"></i> </p>\r\n");
      out.write("                            </td>\r\n");
      out.write("                            <td>20%</td>\r\n");
      out.write("                          </tr>\r\n");
      out.write("                          <tr>\r\n");
      out.write("                            <td>\r\n");
      out.write("                              <p><i class=\"fa fa-square green\"></i>Android </p>\r\n");
      out.write("                            </td>\r\n");
      out.write("                            <td>10%</td>\r\n");
      out.write("                          </tr>\r\n");
      out.write("                          <tr>\r\n");
      out.write("                            <td>\r\n");
      out.write("                              <p><i class=\"fa fa-square purple\"></i>Blackberry </p>\r\n");
      out.write("                            </td>\r\n");
      out.write("                            <td>20%</td>\r\n");
      out.write("                          </tr>\r\n");
      out.write("                          <tr>\r\n");
      out.write("                            <td>\r\n");
      out.write("                              <p><i class=\"fa fa-square aero\"></i>Symbian </p>\r\n");
      out.write("                            </td>\r\n");
      out.write("                            <td>15%</td>\r\n");
      out.write("                          </tr>\r\n");
      out.write("                          <tr>\r\n");
      out.write("                            <td>\r\n");
      out.write("                              <p><i class=\"fa fa-square red\"></i>Others </p>\r\n");
      out.write("                            </td>\r\n");
      out.write("                            <td>30%</td>\r\n");
      out.write("                          </tr>\r\n");
      out.write("                        </table>\r\n");
      out.write("                      </td>\r\n");
      out.write("                    </tr>\r\n");
      out.write("                  </table>\r\n");
      out.write("                </div>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("            <div class=\"col-md-4 col-sm-4 col-xs-12\">\r\n");
      out.write("              <div class=\"x_panel tile fixed_height_320\">\r\n");
      out.write("                <div class=\"x_title\">\r\n");
      out.write("                  <h2>Quick Settings</h2>\r\n");
      out.write("                  <ul class=\"nav navbar-right panel_toolbox\">\r\n");
      out.write("                    <li><a class=\"collapse-link\"><i class=\"fa fa-chevron-up\"></i></a>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li class=\"dropdown\">\r\n");
      out.write("                      <a href=\"#\" class=\"dropdown-toggle\" data-toggle=\"dropdown\" role=\"button\" aria-expanded=\"false\"><i class=\"fa fa-wrench\"></i></a>\r\n");
      out.write("                      <ul class=\"dropdown-menu\" role=\"menu\">\r\n");
      out.write("                        <li><a href=\"#\">Settings 1</a>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li><a href=\"#\">Settings 2</a>\r\n");
      out.write("                        </li>\r\n");
      out.write("                      </ul>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li><a class=\"close-link\"><i class=\"fa fa-close\"></i></a>\r\n");
      out.write("                    </li>\r\n");
      out.write("                  </ul>\r\n");
      out.write("                  <div class=\"clearfix\"></div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"x_content\">\r\n");
      out.write("                  <div class=\"dashboard-widget-content\">\r\n");
      out.write("                    <ul class=\"quick-list\">\r\n");
      out.write("                      <li><i class=\"fa fa-calendar-o\"></i><a href=\"#\">Settings</a>\r\n");
      out.write("                      </li>\r\n");
      out.write("                      <li><i class=\"fa fa-bars\"></i><a href=\"#\">Subscription</a>\r\n");
      out.write("                      </li>\r\n");
      out.write("                      <li><i class=\"fa fa-bar-chart\"></i><a href=\"#\">Auto Renewal</a> </li>\r\n");
      out.write("                      <li><i class=\"fa fa-line-chart\"></i><a href=\"#\">Achievements</a>\r\n");
      out.write("                      </li>\r\n");
      out.write("                      <li><i class=\"fa fa-bar-chart\"></i><a href=\"#\">Auto Renewal</a> </li>\r\n");
      out.write("                      <li><i class=\"fa fa-line-chart\"></i><a href=\"#\">Achievements</a>\r\n");
      out.write("                      </li>\r\n");
      out.write("                      <li><i class=\"fa fa-area-chart\"></i><a href=\"#\">Logout</a>\r\n");
      out.write("                      </li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("\r\n");
      out.write("                    <div class=\"sidebar-widget\">\r\n");
      out.write("                      <h4>Profile Completion</h4>\r\n");
      out.write("                      <canvas width=\"150\" height=\"80\" id=\"foo\" class=\"\" style=\"width: 160px; height: 100px;\"></canvas>\r\n");
      out.write("                      <div class=\"goal-wrapper\">\r\n");
      out.write("                        <span class=\"gauge-value pull-left\">$</span>\r\n");
      out.write("                        <span id=\"gauge-text\" class=\"gauge-value pull-left\">3,200</span>\r\n");
      out.write("                        <span id=\"goal-text\" class=\"goal-value pull-right\">$5,000</span>\r\n");
      out.write("                      </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                  </div>\r\n");
      out.write("                </div>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("          </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("          <div class=\"row\">\r\n");
      out.write("          <!-- Start to do list -->\r\n");
      out.write("         \t  <div class=\"col-md-4 col-sm-4 col-xs-12\">\r\n");
      out.write("                 <div class=\"x_panel\">\r\n");
      out.write("                    <div class=\"x_title\">\r\n");
      out.write("                      <h2>To Do List <small>Sample tasks</small></h2>\r\n");
      out.write("                      <ul class=\"nav navbar-right panel_toolbox\">\r\n");
      out.write("                        <li><a class=\"collapse-link\"><i class=\"fa fa-chevron-up\"></i></a>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li class=\"dropdown\">\r\n");
      out.write("                          <a href=\"#\" class=\"dropdown-toggle\" data-toggle=\"dropdown\" role=\"button\" aria-expanded=\"false\"><i class=\"fa fa-wrench\"></i></a>\r\n");
      out.write("                          <ul class=\"dropdown-menu\" role=\"menu\">\r\n");
      out.write("                            <li><a href=\"#\">Settings 1</a>\r\n");
      out.write("                            </li>\r\n");
      out.write("                            <li><a href=\"#\">Settings 2</a>\r\n");
      out.write("                            </li>\r\n");
      out.write("                          </ul>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li><a class=\"close-link\"><i class=\"fa fa-close\"></i></a>\r\n");
      out.write("                        </li>\r\n");
      out.write("                      </ul>\r\n");
      out.write("                      <div class=\"clearfix\"></div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"x_content\">\r\n");
      out.write("\r\n");
      out.write("                      <div class=\"\">\r\n");
      out.write("                        <ul class=\"to_do\">\r\n");
      out.write("                          <li>\r\n");
      out.write("                            <p>\r\n");
      out.write("                              <input type=\"checkbox\" class=\"flat\"> Schedule meeting with new client </p>\r\n");
      out.write("                          </li>\r\n");
      out.write("                          <li>\r\n");
      out.write("                            <p>\r\n");
      out.write("                              <input type=\"checkbox\" class=\"flat\"> Create email address for new employee</p>\r\n");
      out.write("                          </li>\r\n");
      out.write("                          <li>\r\n");
      out.write("                            <p>\r\n");
      out.write("                              <input type=\"checkbox\" class=\"flat\"> Have IT fix the network printer</p>\r\n");
      out.write("                          </li>\r\n");
      out.write("                          <li>\r\n");
      out.write("                            <p>\r\n");
      out.write("                              <input type=\"checkbox\" class=\"flat\"> Copy backups to offsite location</p>\r\n");
      out.write("                          </li>\r\n");
      out.write("                          <li>\r\n");
      out.write("                            <p>\r\n");
      out.write("                              <input type=\"checkbox\" class=\"flat\"> Create email address for new intern</p>\r\n");
      out.write("                          </li>\r\n");
      out.write("                         <li>\r\n");
      out.write("                            <p>\r\n");
      out.write("                              <input type=\"checkbox\" class=\"flat\"> Attend conference tomorrow</p>\r\n");
      out.write("                          </li>\r\n");
      out.write("                        </ul>\r\n");
      out.write("                      </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                  </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <!-- End to do list -->\r\n");
      out.write("            <div class=\"col-md-8 col-sm-8 col-xs-12\">\r\n");
      out.write("              <div class=\"row\">\r\n");
      out.write("                <div class=\"col-md-12 col-sm-12 col-xs-12\">\r\n");
      out.write("                  <div class=\"x_panel\">\r\n");
      out.write("                    <div class=\"x_title\">\r\n");
      out.write("                      <h2>Visitors location <small>geo-presentation</small></h2>\r\n");
      out.write("                      <ul class=\"nav navbar-right panel_toolbox\">\r\n");
      out.write("                        <li><a class=\"collapse-link\"><i class=\"fa fa-chevron-up\"></i></a>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li class=\"dropdown\">\r\n");
      out.write("                          <a href=\"#\" class=\"dropdown-toggle\" data-toggle=\"dropdown\" role=\"button\" aria-expanded=\"false\"><i class=\"fa fa-wrench\"></i></a>\r\n");
      out.write("                          <ul class=\"dropdown-menu\" role=\"menu\">\r\n");
      out.write("                            <li><a href=\"#\">Settings 1</a>\r\n");
      out.write("                            </li>\r\n");
      out.write("                            <li><a href=\"#\">Settings 2</a>\r\n");
      out.write("                            </li>\r\n");
      out.write("                          </ul>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li><a class=\"close-link\"><i class=\"fa fa-close\"></i></a>\r\n");
      out.write("                        </li>\r\n");
      out.write("                      </ul>\r\n");
      out.write("                      <div class=\"clearfix\"></div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"x_content\">\r\n");
      out.write("                      <div class=\"dashboard-widget-content\">\r\n");
      out.write("                        <div class=\"col-md-4 hidden-small\">\r\n");
      out.write("                          <h2 class=\"line_30\">125.7k Views from 60 countries</h2>\r\n");
      out.write("\r\n");
      out.write("                          <table class=\"countries_list\">\r\n");
      out.write("                            <tbody>\r\n");
      out.write("                              <tr>\r\n");
      out.write("                                <td>United States</td>\r\n");
      out.write("                                <td class=\"fs15 fw700 text-right\">33%</td>\r\n");
      out.write("                              </tr>\r\n");
      out.write("                              <tr>\r\n");
      out.write("                                <td>France</td>\r\n");
      out.write("                                <td class=\"fs15 fw700 text-right\">27%</td>\r\n");
      out.write("                              </tr>\r\n");
      out.write("                              <tr>\r\n");
      out.write("                                <td>Germany</td>\r\n");
      out.write("                                <td class=\"fs15 fw700 text-right\">16%</td>\r\n");
      out.write("                              </tr>\r\n");
      out.write("                              <tr>\r\n");
      out.write("                                <td>Spain</td>\r\n");
      out.write("                                <td class=\"fs15 fw700 text-right\">11%</td>\r\n");
      out.write("                              </tr>\r\n");
      out.write("                              <tr>\r\n");
      out.write("                                <td>Britain</td>\r\n");
      out.write("                                <td class=\"fs15 fw700 text-right\">10%</td>\r\n");
      out.write("                              </tr>\r\n");
      out.write("                            </tbody>\r\n");
      out.write("                          </table>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div id=\"world-map-gdp\" class=\"col-md-8 col-sm-12 col-xs-12\" style=\"height:230px;\"></div>\r\n");
      out.write("                      </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                  </div>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("              </div>\r\n");
      out.write("              <div class=\"row\">\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <!-- /page content -->\r\n");
      out.write("\r\n");
      out.write("        <!-- footer content -->\r\n");
      out.write("        <footer>\r\n");
      out.write("          <div class=\"pull-right\">\r\n");
      out.write("            Team Avengers \r\n");
      out.write("          </div>\r\n");
      out.write("          <div class=\"clearfix\"></div>\r\n");
      out.write("        </footer>\r\n");
      out.write("        <!-- /footer content -->\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <!-- jQuery -->\r\n");
      out.write("    <script src=\"../vendors/jquery/dist/jquery.min.js\"></script>\r\n");
      out.write("    <!-- Bootstrap -->\r\n");
      out.write("    <script src=\"../vendors/bootstrap/dist/js/bootstrap.min.js\"></script>\r\n");
      out.write("    <!-- FastClick -->\r\n");
      out.write("    <script src=\"../vendors/fastclick/lib/fastclick.js\"></script>\r\n");
      out.write("    <!-- NProgress -->\r\n");
      out.write("    <script src=\"../vendors/nprogress/nprogress.js\"></script>\r\n");
      out.write("    <!-- Chart.js -->\r\n");
      out.write("    <script src=\"../vendors/Chart.js/dist/Chart.min.js\"></script>\r\n");
      out.write("    <!-- gauge.js -->\r\n");
      out.write("    <script src=\"../vendors/bernii/gauge.js/dist/gauge.min.js\"></script>\r\n");
      out.write("    <!-- bootstrap-progressbar -->\r\n");
      out.write("    <script src=\"../vendors/bootstrap-progressbar/bootstrap-progressbar.min.js\"></script>\r\n");
      out.write("    <!-- iCheck -->\r\n");
      out.write("    <script src=\"../vendors/iCheck/icheck.min.js\"></script>\r\n");
      out.write("    <!-- Skycons -->\r\n");
      out.write("    <script src=\"../vendors/skycons/skycons.js\"></script>\r\n");
      out.write("    <!-- Flot -->\r\n");
      out.write("    <script src=\"../vendors/Flot/jquery.flot.js\"></script>\r\n");
      out.write("    <script src=\"../vendors/Flot/jquery.flot.pie.js\"></script>\r\n");
      out.write("    <script src=\"../vendors/Flot/jquery.flot.time.js\"></script>\r\n");
      out.write("    <script src=\"../vendors/Flot/jquery.flot.stack.js\"></script>\r\n");
      out.write("    <script src=\"../vendors/Flot/jquery.flot.resize.js\"></script>\r\n");
      out.write("    <!-- Flot plugins -->\r\n");
      out.write("    <script src=\"js/flot/jquery.flot.orderBars.js\"></script>\r\n");
      out.write("    <script src=\"js/flot/date.js\"></script>\r\n");
      out.write("    <script src=\"js/flot/jquery.flot.spline.js\"></script>\r\n");
      out.write("    <script src=\"js/flot/curvedLines.js\"></script>\r\n");
      out.write("    <!-- jVectorMap -->\r\n");
      out.write("    <script src=\"js/maps/jquery-jvectormap-2.0.3.min.js\"></script>\r\n");
      out.write("    <!-- bootstrap-daterangepicker -->\r\n");
      out.write("    <script src=\"js/moment/moment.min.js\"></script>\r\n");
      out.write("    <script src=\"js/datepicker/daterangepicker.js\"></script>\r\n");
      out.write("\r\n");
      out.write("    <!-- Custom Theme Scripts -->\r\n");
      out.write("    <script src=\"js/custom.js\"></script>\r\n");
      out.write("\r\n");
      out.write("    <!-- Flot -->\r\n");
      out.write("    <script>\r\n");
      out.write("      $(document).ready(function() {\r\n");
      out.write("        var data1 = [\r\n");
      out.write("          [gd(2012, 1, 1), 17],\r\n");
      out.write("          [gd(2012, 1, 2), 74],\r\n");
      out.write("          [gd(2012, 1, 3), 6],\r\n");
      out.write("          [gd(2012, 1, 4), 39],\r\n");
      out.write("          [gd(2012, 1, 5), 20],\r\n");
      out.write("          [gd(2012, 1, 6), 85],\r\n");
      out.write("          [gd(2012, 1, 7), 7]\r\n");
      out.write("        ];\r\n");
      out.write("\r\n");
      out.write("        var data2 = [\r\n");
      out.write("          [gd(2012, 1, 1), 82],\r\n");
      out.write("          [gd(2012, 1, 2), 23],\r\n");
      out.write("          [gd(2012, 1, 3), 66],\r\n");
      out.write("          [gd(2012, 1, 4), 9],\r\n");
      out.write("          [gd(2012, 1, 5), 119],\r\n");
      out.write("          [gd(2012, 1, 6), 6],\r\n");
      out.write("          [gd(2012, 1, 7), 9]\r\n");
      out.write("        ];\r\n");
      out.write("        $(\"#canvas_dahs\").length && $.plot($(\"#canvas_dahs\"), [\r\n");
      out.write("          data1, data2\r\n");
      out.write("        ], {\r\n");
      out.write("          series: {\r\n");
      out.write("            lines: {\r\n");
      out.write("              show: false,\r\n");
      out.write("              fill: true\r\n");
      out.write("            },\r\n");
      out.write("            splines: {\r\n");
      out.write("              show: true,\r\n");
      out.write("              tension: 0.4,\r\n");
      out.write("              lineWidth: 1,\r\n");
      out.write("              fill: 0.4\r\n");
      out.write("            },\r\n");
      out.write("            points: {\r\n");
      out.write("              radius: 0,\r\n");
      out.write("              show: true\r\n");
      out.write("            },\r\n");
      out.write("            shadowSize: 2\r\n");
      out.write("          },\r\n");
      out.write("          grid: {\r\n");
      out.write("            verticalLines: true,\r\n");
      out.write("            hoverable: true,\r\n");
      out.write("            clickable: true,\r\n");
      out.write("            tickColor: \"#d5d5d5\",\r\n");
      out.write("            borderWidth: 1,\r\n");
      out.write("            color: '#fff'\r\n");
      out.write("          },\r\n");
      out.write("          colors: [\"rgba(38, 185, 154, 0.38)\", \"rgba(3, 88, 106, 0.38)\"],\r\n");
      out.write("          xaxis: {\r\n");
      out.write("            tickColor: \"rgba(51, 51, 51, 0.06)\",\r\n");
      out.write("            mode: \"time\",\r\n");
      out.write("            tickSize: [1, \"day\"],\r\n");
      out.write("            //tickLength: 10,\r\n");
      out.write("            axisLabel: \"Date\",\r\n");
      out.write("            axisLabelUseCanvas: true,\r\n");
      out.write("            axisLabelFontSizePixels: 12,\r\n");
      out.write("            axisLabelFontFamily: 'Verdana, Arial',\r\n");
      out.write("            axisLabelPadding: 10\r\n");
      out.write("          },\r\n");
      out.write("          yaxis: {\r\n");
      out.write("            ticks: 8,\r\n");
      out.write("            tickColor: \"rgba(51, 51, 51, 0.06)\",\r\n");
      out.write("          },\r\n");
      out.write("          tooltip: false\r\n");
      out.write("        });\r\n");
      out.write("\r\n");
      out.write("        function gd(year, month, day) {\r\n");
      out.write("          return new Date(year, month - 1, day).getTime();\r\n");
      out.write("        }\r\n");
      out.write("      });\r\n");
      out.write("    </script>\r\n");
      out.write("    <!-- /Flot -->\r\n");
      out.write("\r\n");
      out.write("    <!-- jVectorMap -->\r\n");
      out.write("    <script src=\"js/maps/jquery-jvectormap-world-mill-en.js\"></script>\r\n");
      out.write("    <script src=\"js/maps/jquery-jvectormap-us-aea-en.js\"></script>\r\n");
      out.write("    <script src=\"js/maps/gdp-data.js\"></script>\r\n");
      out.write("    <script>\r\n");
      out.write("      $(document).ready(function(){\r\n");
      out.write("        $('#world-map-gdp').vectorMap({\r\n");
      out.write("          map: 'world_mill_en',\r\n");
      out.write("          backgroundColor: 'transparent',\r\n");
      out.write("          zoomOnScroll: false,\r\n");
      out.write("          series: {\r\n");
      out.write("            regions: [{\r\n");
      out.write("              values: gdpData,\r\n");
      out.write("              scale: ['#E6F2F0', '#149B7E'],\r\n");
      out.write("              normalizeFunction: 'polynomial'\r\n");
      out.write("            }]\r\n");
      out.write("          },\r\n");
      out.write("          onRegionTipShow: function(e, el, code) {\r\n");
      out.write("            el.html(el.html() + ' (GDP - ' + gdpData[code] + ')');\r\n");
      out.write("          }\r\n");
      out.write("        });\r\n");
      out.write("      });\r\n");
      out.write("    </script>\r\n");
      out.write("    <!-- /jVectorMap -->\r\n");
      out.write("\r\n");
      out.write("    <!-- Skycons -->\r\n");
      out.write("    <script>\r\n");
      out.write("      $(document).ready(function() {\r\n");
      out.write("        var icons = new Skycons({\r\n");
      out.write("            \"color\": \"#73879C\"\r\n");
      out.write("          }),\r\n");
      out.write("          list = [\r\n");
      out.write("            \"clear-day\", \"clear-night\", \"partly-cloudy-day\",\r\n");
      out.write("            \"partly-cloudy-night\", \"cloudy\", \"rain\", \"sleet\", \"snow\", \"wind\",\r\n");
      out.write("            \"fog\"\r\n");
      out.write("          ],\r\n");
      out.write("          i;\r\n");
      out.write("\r\n");
      out.write("        for (i = list.length; i--;)\r\n");
      out.write("          icons.set(list[i], list[i]);\r\n");
      out.write("\r\n");
      out.write("        icons.play();\r\n");
      out.write("      });\r\n");
      out.write("    </script>\r\n");
      out.write("    <!-- /Skycons -->\r\n");
      out.write("\r\n");
      out.write("    <!-- Doughnut Chart -->\r\n");
      out.write("    <script>\r\n");
      out.write("      $(document).ready(function(){\r\n");
      out.write("        var options = {\r\n");
      out.write("          legend: false,\r\n");
      out.write("          responsive: false\r\n");
      out.write("        };\r\n");
      out.write("\r\n");
      out.write("        new Chart(document.getElementById(\"canvas1\"), {\r\n");
      out.write("          type: 'doughnut',\r\n");
      out.write("          tooltipFillColor: \"rgba(51, 51, 51, 0.55)\",\r\n");
      out.write("          data: {\r\n");
      out.write("            labels: [\r\n");
      out.write("              \"Symbian\",\r\n");
      out.write("              \"Blackberry\",\r\n");
      out.write("              \"Other\",\r\n");
      out.write("              \"Android\",\r\n");
      out.write("              \"IOS\"\r\n");
      out.write("            ],\r\n");
      out.write("            datasets: [{\r\n");
      out.write("              data: [15, 20, 30, 10, 30],\r\n");
      out.write("              backgroundColor: [\r\n");
      out.write("                \"#BDC3C7\",\r\n");
      out.write("                \"#9B59B6\",\r\n");
      out.write("                \"#E74C3C\",\r\n");
      out.write("                \"#26B99A\",\r\n");
      out.write("                \"#3498DB\"\r\n");
      out.write("              ],\r\n");
      out.write("              hoverBackgroundColor: [\r\n");
      out.write("                \"#CFD4D8\",\r\n");
      out.write("                \"#B370CF\",\r\n");
      out.write("                \"#E95E4F\",\r\n");
      out.write("                \"#36CAAB\",\r\n");
      out.write("                \"#49A9EA\"\r\n");
      out.write("              ]\r\n");
      out.write("            }]\r\n");
      out.write("          },\r\n");
      out.write("          options: options\r\n");
      out.write("        });\r\n");
      out.write("      });\r\n");
      out.write("    </script>\r\n");
      out.write("    <!-- /Doughnut Chart -->\r\n");
      out.write("    \r\n");
      out.write("   \r\n");
      out.write("\r\n");
      out.write("    <!-- gauge.js -->\r\n");
      out.write("    <script>\r\n");
      out.write("      var opts = {\r\n");
      out.write("          lines: 12,\r\n");
      out.write("          angle: 0,\r\n");
      out.write("          lineWidth: 0.4,\r\n");
      out.write("          pointer: {\r\n");
      out.write("              length: 0.75,\r\n");
      out.write("              strokeWidth: 0.042,\r\n");
      out.write("              color: '#1D212A'\r\n");
      out.write("          },\r\n");
      out.write("          limitMax: 'false',\r\n");
      out.write("          colorStart: '#1ABC9C',\r\n");
      out.write("          colorStop: '#1ABC9C',\r\n");
      out.write("          strokeColor: '#F0F3F3',\r\n");
      out.write("          generateGradient: true\r\n");
      out.write("      };\r\n");
      out.write("      var target = document.getElementById('foo'),\r\n");
      out.write("          gauge = new Gauge(target).setOptions(opts);\r\n");
      out.write("\r\n");
      out.write("      gauge.maxValue = 6000;\r\n");
      out.write("      gauge.animationSpeed = 32;\r\n");
      out.write("      gauge.set(3200);\r\n");
      out.write("      gauge.setTextField(document.getElementById(\"gauge-text\"));\r\n");
      out.write("    </script>\r\n");
      out.write("    <!-- /gauge.js -->\r\n");
      out.write("  </body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fforEach_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005fforEach_005f0.setParent(null);
    // /EmployeeDetails.jsp(204,14) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fforEach_005f0.setVar("EmployeeDetails");
    // /EmployeeDetails.jsp(204,14) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
    _jspx_th_c_005fforEach_005f0.setItems(new org.apache.jasper.el.JspValueExpression("/EmployeeDetails.jsp(204,14) '${Em}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${Em}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
    int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
    try {
      int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
      if (_jspx_eval_c_005fforEach_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("                <h3>\r\n");
          out.write("                ");
          if (_jspx_meth_c_005fout_005f0(_jspx_th_c_005fforEach_005f0, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f0))
            return true;
          out.write("\r\n");
          out.write("         \r\n");
          out.write("                </h3>\r\n");
          out.write("                       \r\n");
          out.write("                <ul class=\"nav side-menu\">\r\n");
          out.write("                  <li><a><i class=\"fa fa-home\"></i> Console </a></li>\r\n");
          out.write("                  <li><a href=\"form_validation.html\"><i class=\"fa fa-edit\"></i> Employee  Form </a></li>\r\n");
          out.write("                   \r\n");
          out.write("                  <li><a><i class=\"fa fa-table\"></i> Tables <span class=\"fa fa-chevron-down\"></span></a>\r\n");
          out.write("                    <ul class=\"nav child_menu\">\r\n");
          out.write("                      <li><a href=\"tables.html\">Tables</a>\r\n");
          out.write("                      </li>\r\n");
          out.write("                      <li><a href=\"tables_dynamic.html\">Table Dynamic</a>\r\n");
          out.write("                      </li>\r\n");
          out.write("                    </ul>\r\n");
          out.write("                  </li>\r\n");
          out.write("                  <li><a><i class=\"fa fa-bar-chart-o\"></i> Data Presentation <span class=\"fa fa-chevron-down\"></span></a>\r\n");
          out.write("                    <ul class=\"nav child_menu\">\r\n");
          out.write("                      <li><a href=\"chartjs.html\">Chart JS</a>\r\n");
          out.write("                      </li>\r\n");
          out.write("                      <li><a href=\"chartjs2.html\">Chart JS2</a>\r\n");
          out.write("                      </li>\r\n");
          out.write("                      <li><a href=\"morisjs.html\">Moris JS</a>\r\n");
          out.write("                      </li>\r\n");
          out.write("                      <li><a href=\"echarts.html\">ECharts </a>\r\n");
          out.write("                      </li>\r\n");
          out.write("                      <li><a href=\"other_charts.html\">Other Charts </a>\r\n");
          out.write("                      </li>\r\n");
          out.write("                    </ul>\r\n");
          out.write("                  </li>\r\n");
          out.write("                </ul>\r\n");
          out.write("              </div>\r\n");
          out.write("             \r\n");
          out.write("            </div>\r\n");
          out.write("            <!-- /sidebar menu -->\r\n");
          out.write("\r\n");
          out.write("          </div>\r\n");
          out.write("        </div>\r\n");
          out.write("\r\n");
          out.write("        <!-- top navigation -->\r\n");
          out.write("        <div class=\"top_nav\">\r\n");
          out.write("\r\n");
          out.write("          <div class=\"nav_menu\">\r\n");
          out.write("            <nav class=\"\" role=\"navigation\">\r\n");
          out.write("              <div class=\"nav toggle\">\r\n");
          out.write("                <a id=\"menu_toggle\"><i class=\"fa fa-bars\"></i></a>\r\n");
          out.write("              </div>\r\n");
          out.write("\r\n");
          out.write("              <ul class=\"nav navbar-nav navbar-right\">\r\n");
          out.write("                <li class=\"\">\r\n");
          out.write("                  <a href=\"javascript:;\" class=\"user-profile dropdown-toggle\" data-toggle=\"dropdown\" aria-expanded=\"false\">\r\n");
          out.write("                    <img src=\"images/img.jpg\" alt=\"\">");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${EmployeeDetails.username}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\r\n");
          out.write("                    <span class=\" fa fa-angle-down\"></span>\r\n");
          out.write("                  </a>\r\n");
          out.write("                  <ul class=\"dropdown-menu dropdown-usermenu pull-right\">\r\n");
          out.write("                  \r\n");
          out.write("                    <li><a href=\"login.html\"><i class=\"fa fa-sign-out pull-right\"></i> Log Out</a>\r\n");
          out.write("                    </li>\r\n");
          out.write("                  </ul>\r\n");
          out.write("                </li>\r\n");
          int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fforEach_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } catch (java.lang.Throwable _jspx_exception) {
      while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
        out = _jspx_page_context.popBody();
      _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
    } finally {
      _jspx_th_c_005fforEach_005f0.doFinally();
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f0);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fout_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fforEach_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:out
    org.apache.taglibs.standard.tag.rt.core.OutTag _jspx_th_c_005fout_005f0 = (org.apache.taglibs.standard.tag.rt.core.OutTag) _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.OutTag.class);
    _jspx_th_c_005fout_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005fout_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fforEach_005f0);
    // /EmployeeDetails.jsp(206,16) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fout_005f0.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${EmployeeDetails.jobTitle}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
    int _jspx_eval_c_005fout_005f0 = _jspx_th_c_005fout_005f0.doStartTag();
    if (_jspx_th_c_005fout_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005fout_005f0);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005fout_005f0);
    return false;
  }
}
